jwt:
  secret: aboba
  accessTokenTTL: 30m
  refreshTokenTTL: 48h
  issuer: chat-backend
app:
  isDev: true
  isTesting: false
  logLevel: DEBUG
server:
  host: localhost
  port: 8000
postgres:
  host: localhost
  port: 5434
  database: chat
  user: postgres
  password: postgres